### ISSUE TITLE
Change members avatars colors

### ISSUE THREAD

**Issue by swouf** [graasp/graasp-app-task-management#27]

**Comment by spaenleh** [comment]
I am not sure what you want to do exactly, but i can suggest [something i did in my app](https://github.com/graasp/graasp-app-code-capsule/blob/a977ce2b52a8e270cacad30a35dc86e62c4aca63/src/components/layout/CustomAvatar.tsx#L9). So i wanted that each user has a unique color based on their username, and answer came from SO !

**Comment by swouf** [comment]
Thank you for the suggestion!
